version: "3.8"

services:
  frontend:
    container_name: frontend
    build: frontend
    networks:
      - frontend
    ports:
      - 80:80
    depends_on:
      - backend
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/nginx.conf

  backend:
    container_name: backend
    build: backend
    volumes:
      - ./backend/src:/usr/src
    links:
      - database
    ports:
      - 5000:5000
    environment:
      APP_SETTINGS: tamane
      POSTGRES_PASSWORD: mziane
      POSTGRES_DB: cars
      DATABASE_URL: postgresql+psycopg2://tamane:mziane@database:5432/cars
    networks:
      - db_network
      - frontend

  database:
    container_name: database
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: tamane
      POSTGRES_PASSWORD: mziane
      POSTGRES_DB: cars
    ports:
      - 5435:5432
    volumes:
    - db_volume:/var/lib/postgresql
    networks:
      db_network:

networks:
 db_network:
 frontend:

volumes:
  db_volume: