version: "3.8"

services:
  backend:
    container_name: backend
    build: backend
    volumes:
      - ./backend/src:/usr/src
    links:
      - database
    ports:
      - 5000:5000
    environment:
      APP_SETTINGS: tamane
      POSTGRES_PASSWORD: mziane
      POSTGRES_DB: cars
      DATABASE_URL: postgresql+psycopg2://tamane:mziane@database:5432/cars
    networks:
      some_network:
  database:
    container_name: database
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: tamane
      POSTGRES_PASSWORD: mziane
      POSTGRES_DB: cars
    ports:
      - 5435:5432
    networks:
      some_network:
networks:
 some_network: